[env]
TERM                  = "alacritty"

[font]
normal                = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold                  = { family = "FiraCode Nerd Font Mono", style = "Regular" }
italic                = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold_italic           = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size                  = 14
offset                = { x = 0, y = 1 }
glyph_offset          = { x = 0, y = 0 }
builtin_box_drawing   = true

[scrolling]
history               = 5000
multiplier            = 3

[bell]
animation             = "EaseOutExpo"
duration              = 3
color                 = "#C0C5CE"
command               = { program = "notify-send", args = ["alacritty", "bell",] }

[cursor]
blink_interval        = 500
blink_timeout         = 0
#unfocused_hollow      = true
#thickness             = 0.15

[cursor.style]
shape                 = "Block"
blinking              = "Off"

[cursor.vi_mode_style]
shape                 = "Block"
blinking              = "Off"

[mouse]
hide_when_typing      = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]

[hints]
alphabet              = "jfkdls;ahgurieowpq"
