[notebook]
dir = "$ZK_NOTEBOOK_DIR"

[note]
language = "en"
default-title = "Untitled"
filename = "{{slug title}}"
extension = "md"
template = "default.md"
# id-charset = "alphanum"
# id-length = 8
# id-case = "lower"

[format.markdown]
hashtags = true
colon-tags = true
multiword-tags = false

[tool]
fzf-preview = "bat -p --color always {-1}"

[group.daily]
paths = ["self/daily"]

[group.daily.note]
filename = "{{format-date now}}"
template = "daily.md"

[filter]
recents = "--sort created- --created-after 'last two weeks'"

[alias]

# Edit the last modified note.
edlast = "zk edit --limit 1 --sort modified- $@"

# Edit the notes selected interactively among the notes created the last two weeks.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# Show a random note.
lucky = "zk list --quiet --format full --sort random --limit 1"

# Create note with defalut template
n = "zk new 0_inbox --title=$@"

# Create new daily journal
d = "zk new --no-input --group=daily self/daily"

# LSP (EDITOR INTEGRATION)
[lsp]

[lsp.completion]
use-additional-text-edits = true

[lsp.diagnostics]
# Report titles of wiki-links as hints.
wiki-title = "hint"
# Warn for dead links between notes.
dead-link = "error"
