directory: ~/mus
library: ~/.cache/beets/musiclibrary.blb
# pluginpath:
#   - /usr/lib/python2.7/site-packages/beetsplug
#   - ~/code/python/beetsplug
import:
  move: yes
  timid: yes
paths:
  default: '%the{$albumartist}/$year $album%aunique{}/$track $title'
  comp: '_Compilations/$year $album%aunique{}/$track $title'
  albumtype:soundtrack: '_Soundtracks/$year $album%aunique{}/$track $title'
  singleton: '_Singles/%the{$albumartist} - $title'
match:
  preferred:
    countries: ['US', 'GB|UK']
    media: ['CD', 'Digital Media|File']
    original_year: yes
original_date: yes
format_album: '$albumartist - $album ($year)'
clutter: [ "Thumbs.db", ".DS_Store", "*jpg", "*png" ]
plugins: lastgenre scrub the zero ftintitle mpdupdate duplicates info lastimport mbsync play discogs
zero:
  fields: month day comments lyrics albumartist_credit artist_credit
#importfeeds:
#  formats: m3u
#  relative_to: /mnt/media/music/
#  dir: /mnt/media/music/_Playlists/
#  m3u_name: new_albums.m3u
play:
  relative_to: ~/mus/
  command: mpd-m3u-handler.sh
replaygain:
  auto: no
  albumgain: yes
mpd:
  host: music.host
  port: 6600
echonest:
  auto: no
  codegen: echoprint-codegen
  apikey: {{ ECHONEST_TOKEN }}
