---

# supported options are "docker" and "podman"
container-engine: docker

log:
  enabled: true
  path: ~/.cache/dive.log
  level: info

# Note: you can specify multiple bindings by separating values with a comma.
# Note: UI hinting is derived from the first binding
keybinding:
  # Global bindings
  quit: ctrl+c, ctrl+q
  toggle-view: ctrl+h, ctrl+l, tab
  filter-files: ctrl+f, ctrl+slash

  # Layer view specific bindings
  compare-all: ctrl+p
  compare-layer: ctrl+y

  # File view specific bindings
  toggle-collapse-dir: space
  toggle-added-files: ctrl+b
  toggle-removed-files: ctrl+r
  toggle-modified-files: ctrl+m
  toggle-unmodified-files: ctrl+u
  toggle-filetree-attributes: ctrl+s
  page-up: ctrl+u, pgup
  page-down: ctrl+d, pgdn

diff:
  hide:
    - unmodified

filetree:
  collapse-dir: true
  pane-width: 0.5
  show-attributes: true

layer:
  show-aggregated-changes: true
